# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'
#' Input Matrix
#'
#' Mini-batch-k-means for both matrix and HDF5Matrix
#'
#'@param data numeric matrix or integer matrix or HDF5Matrix
#'@return a list with the following attributes: centroids, WCSS_per_cluster, best_initialization, iters_per_initialization
#'@details
#'\strong{random}: random selection of data rows as initial centroids
#'
#'@references
#'https://github.com/mlampros/ClusterR
#'
#' @export
readInput <- function(data) {
    .Call(`_Btree_readInput`, data)
}

